<footer id="footer" class="footer">
    <div class="container copyright text-center mt-4">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">EcoBuddy</strong> <span>All Rights Reserved</span></p>
    </div>

</footer>

<!-- Scroll Top -->
<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="<?= BASE_URL ?>/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/php-email-form/validate.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/aos/aos.js"></script>
<script src="<?= BASE_URL ?>/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="<?= BASE_URL ?>/assets/js/jquery.min.js"></script>
<script src="<?= BASE_URL ?>/assets/js/datatables.js"></script>

<!-- Main JS File -->
<script src="<?= BASE_URL ?>/assets/js/main.js"></script>
<script src="<?= BASE_URL ?>/assets/js/script.js"></script>
<?php

if (isset($script)) {
    include_once $script;
}

?>

</body>

</html>